### ISSUE TITLE
difference between data in analysis/ folder and gated fcs files

### ISSUE THREAD

**Issue by Ivy-ops** [astrolabediagnostics/orloj#5]
Hi developer, 

I am new to the Cytof data and have some questions below. I look forward to hearing your suggestions. 

--Part 1
I try to read the files in the analysis folder with the below code. 
```
experiment <- orloj::loadExperiment('~/Downloads/')
sample <- orloj::loadSample(experiment, sample_name = "**")
orloj::sampleSummary(sample)
```
Output nicely gives me 
```
An Astrolabe sample with 33122 cells and 72 channels
0 beads, 0 debris and doublets, and 0 dead cells
```
I checked some of the columns of the expression data, is shown below 
![image](https://user-images.githubusercontent.com/61573164/137519878-71f87398-6d07-4579-bb64-182a1671fbd2.png)
---Part 2
As I read the tutorial of orloj, gated fcs files (labelled FCS Files in the Astrolabe platform) can also be downloaded and used. Thus I also read the fcs file in /fcs/ folder downloaded from the Astrolabe analyzed result. Code I applied is shown below
```
fs = read.flowSet(file, truncate_max_range = FALSE, transformation = FALSE)
expr <- flowCore::fsApply(fs, exprs)
```

However, the dimension of the expression data is 207343 cells. And I check some columns of the expression. 

![image](https://user-images.githubusercontent.com/61573164/137519695-a5966e3a-0207-4156-ae07-b497296f5380.png)

The comparison of the two data makes me confused. I have some questions.
(1) Tutorial shows "After loading a sample, you can access its FCS data and cell subset assignments:", it seems that the files I get from '/analysis/' folder are randomly subset data. Can I get the full cell data from the analysis folder?
(2)The "Assignment, Profiling, Compartment" columns are shown as numbers in read-in FCS files. What do these numbers mean? Is there a corresponding cell type name for these numbers (Similar to the names of the assignments in part1)?

Much appreciated!

-Ivy

**Comment by dtelad11** [comment]
Thanks Ivy! We are unable to provide technical support over Github. Please contact us at support@astrolabediagnostics.com and include your experiment ID (which is under the "Settings" tab).
